### PR TITLE
add vim controls (h,j,k,l) to move robots

### PR DESCRIPTION
**Pull request by aalok-sathe**
added vim controls (`h, j, k, l`) to move robots

### CODE REVIEW

**Comment by rubo77** [comment]
why did you close this?

**Comment by aalok-sathe** [comment]
The branch I PRed contains commits in excess of this feature, the title of the PR suggests it would only be the controls. So it would not be appropriate to merge this anymore.

**Comment by aalok-sathe** [comment]
the only relevant commit is 75a2ac

**Comment by rubo77** [comment]
Do you create a new PR?

**Pull request closed without merging**
